from typing import Protocol


class LabelledCounter(Protocol):
    def labels(self, **kwargs: str) -> "LabelledCounter": ...
    def inc(self, amount: float = 1): ...


class LabelledGauge(Protocol):
    def labels(self, **kwargs: str) -> "LabelledGauge": ...
    def set(self, value: float): ...


class LabelledHistogram(Protocol):
    def labels(self, **kwargs: str) -> "LabelledHistogram": ...
    def observe(self, value: float): ...


LabelledMetric = LabelledCounter | LabelledGauge | LabelledHistogram
