import pytest

from tests.assets.support.mixin import Mixin

def test_mixin_itself_cannot_be_instantiated():
    class A(Mixin): ...
    with pytest.raises(TypeError):
        A()

def test_pure_mixin_stack_cannot_be_instantiated():
    class A(Mixin): ...
    class B(Mixin): ...
    class C(A, B): ...
    with pytest.raises(TypeError):
        C()

def test_mixin_with_nonmixin_base_is_instantiable_either_order():
    class Base: ...
    class A(Mixin): ...

    class LeftFirst(A, Base): ...
    class RightFirst(Base, A): ...

    # Should not raise
    LeftFirst()
    RightFirst()

def test_deep_chain_pure_until_concrete_then_ok():
    class A(Mixin): ...
    class B(A): ...
    class C(B): ...
    class Base: ...
    class D(C, Base): ...
    # Only when Base is included does instantiation become legal
    with pytest.raises(TypeError):
        C()
    D()  # ok

def test_multiple_mixins_plus_concrete_is_ok():
    class A(Mixin): ...
    class B(Mixin): ...
    class C(Mixin): ...
    class Base: ...
    class X(A, B, C, Base): ...
    class Y(Base, A, B, C): ...
    X()
    Y()

def test_error_is_typeerror_and_mentions_class_name():
    class A(Mixin): ...
    with pytest.raises(TypeError) as exc:
        A()
    # Message should reference the failing class name
    assert "A" in str(exc.value)

def test_subclass_of_concrete_remains_instantiable_even_if_mixins_added():
    class Base: ...
    class A(Mixin): ...
    class B(Mixin): ...

    class Concrete(Base): ...
    class ConcreteWithMixins(A, B, Concrete): ...
    class Derived(ConcreteWithMixins): ...

    Concrete()
    ConcreteWithMixins()
    Derived()
