# Label Keys
LABEL_PIPELINE = "pipeline"

LABEL_RESOURCE = "resource"
LABEL_RESOURCE_METHOD = "resource_method"

LABEL_MINION = "minion"
LABEL_MINION_COMPOSITE_KEY = "minion_composite_key"
LABEL_MINION_WORKFLOW_STEP = "minion_workflow_step"
LABEL_MINION_WORKFLOW_PERSISTENCE_CHECKPOINT_TYPE = "minion_workflow_persistence_checkpoint_type"
LABEL_MINION_WORKFLOW_PERSISTENCE_FAILURE_STAGE = "minion_workflow_persistence_failure_stage"
LABEL_MINION_WORKFLOW_PERSISTENCE_OPERATION = "minion_workflow_persistence_operation"
LABEL_MINION_WORKFLOW_PERSISTENCE_POLICY = "minion_workflow_persistence_policy"
LABEL_MINION_WORKFLOW_PERSISTENCE_RETRYABLE = "minion_workflow_persistence_retryable"

LABEL_ERROR_TYPE = "error_type"
LABEL_STATUS = "status"
LABEL_STATE_STORE = "state_store"

# Pipeline Metric Names
PIPELINE_EVENT_PRODUCED_TOTAL = "pipeline_event_produced_total"
PIPELINE_EVENT_FANOUT_TOTAL = "pipeline_event_fanout_total"
PIPELINE_ERROR_TOTAL = "pipeline_error_total"

# Resource Metric Names
RESOURCE_SERVES_TOTAL = "resource_serves_total"
RESOURCE_LATENCY_SECONDS = "resource_latency_seconds"
RESOURCE_ERROR_TOTAL = "resource_error_total"

# Minion Metric Names
MINION_WORKFLOW_STARTED_TOTAL = "minion_workflow_started_total"
MINION_WORKFLOW_INFLIGHT_GAUGE = "minion_workflow_inflight_gauge"
MINION_WORKFLOW_ABORTED_TOTAL = "minion_workflow_aborted_total"
MINION_WORKFLOW_FAILED_TOTAL = "minion_workflow_failed_total"
MINION_WORKFLOW_SUCCEEDED_TOTAL = "minion_workflow_succeeded_total"
MINION_WORKFLOW_DURATION_SECONDS = "minion_workflow_duration_seconds"

MINION_WORKFLOW_PERSISTENCE_ATTEMPTS_TOTAL = "minion_workflow_persistence_attempts_total"
MINION_WORKFLOW_PERSISTENCE_SUCCEEDED_TOTAL = "minion_workflow_persistence_succeeded_total"
MINION_WORKFLOW_PERSISTENCE_FAILURES_TOTAL = "minion_workflow_persistence_failures_total"
MINION_WORKFLOW_PERSISTENCE_DURATION_SECONDS = "minion_workflow_persistence_duration_seconds"
MINION_WORKFLOW_PERSISTENCE_BLOCKED_GAUGE = "minion_workflow_persistence_blocked_gauge"

MINION_WORKFLOW_STEP_STARTED_TOTAL = "minion_workflow_step_started_total"
MINION_WORKFLOW_STEP_INFLIGHT_GAUGE = "minion_workflow_step_inflight_gauge"
MINION_WORKFLOW_STEP_ABORTED_TOTAL = "minion_workflow_step_aborted_total"
MINION_WORKFLOW_STEP_FAILED_TOTAL = "minion_workflow_step_failed_total"
MINION_WORKFLOW_STEP_SUCCEEDED_TOTAL = "minion_workflow_step_succeeded_total"
MINION_WORKFLOW_STEP_DURATION_SECONDS = "minion_workflow_step_duration_seconds"

# General Metric Names
SYSTEM_MEMORY_USED_PERCENT = "system_memory_used_percent"
SYSTEM_CPU_USED_PERCENT = "system_cpu_used_percent"

PROCESS_MEMORY_USED_PERCENT = "process_memory_used_percent"
PROCESS_CPU_USED_PERCENT = "process_cpu_used_percent"

# Metrics Label Names
METRIC_LABEL_NAMES = {
    PIPELINE_EVENT_PRODUCED_TOTAL: [LABEL_PIPELINE],
    PIPELINE_EVENT_FANOUT_TOTAL: [LABEL_PIPELINE, LABEL_MINION_COMPOSITE_KEY],
    PIPELINE_ERROR_TOTAL: [LABEL_PIPELINE, LABEL_ERROR_TYPE],

    RESOURCE_SERVES_TOTAL: [LABEL_RESOURCE, LABEL_RESOURCE_METHOD],
    RESOURCE_LATENCY_SECONDS: [LABEL_RESOURCE, LABEL_RESOURCE_METHOD],
    RESOURCE_ERROR_TOTAL: [LABEL_RESOURCE, LABEL_RESOURCE_METHOD, LABEL_ERROR_TYPE],

    MINION_WORKFLOW_STARTED_TOTAL: [LABEL_MINION_COMPOSITE_KEY],
    MINION_WORKFLOW_INFLIGHT_GAUGE: [LABEL_MINION_COMPOSITE_KEY],
    MINION_WORKFLOW_ABORTED_TOTAL: [LABEL_MINION_COMPOSITE_KEY],
    MINION_WORKFLOW_FAILED_TOTAL: [LABEL_MINION_COMPOSITE_KEY, LABEL_ERROR_TYPE],
    MINION_WORKFLOW_SUCCEEDED_TOTAL: [LABEL_MINION_COMPOSITE_KEY],
    MINION_WORKFLOW_DURATION_SECONDS: [LABEL_MINION_COMPOSITE_KEY, LABEL_STATUS],

    MINION_WORKFLOW_PERSISTENCE_ATTEMPTS_TOTAL: [
        LABEL_MINION_COMPOSITE_KEY,
        LABEL_MINION_WORKFLOW_PERSISTENCE_CHECKPOINT_TYPE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_OPERATION,
        LABEL_MINION_WORKFLOW_PERSISTENCE_POLICY,
        LABEL_STATE_STORE,
    ],
    MINION_WORKFLOW_PERSISTENCE_SUCCEEDED_TOTAL: [
        LABEL_MINION_COMPOSITE_KEY,
        LABEL_MINION_WORKFLOW_PERSISTENCE_CHECKPOINT_TYPE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_OPERATION,
        LABEL_MINION_WORKFLOW_PERSISTENCE_POLICY,
        LABEL_STATE_STORE,
    ],
    MINION_WORKFLOW_PERSISTENCE_FAILURES_TOTAL: [
        LABEL_MINION_COMPOSITE_KEY,
        LABEL_MINION_WORKFLOW_PERSISTENCE_CHECKPOINT_TYPE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_OPERATION,
        LABEL_MINION_WORKFLOW_PERSISTENCE_FAILURE_STAGE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_RETRYABLE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_POLICY,
        LABEL_STATE_STORE,
    ],
    MINION_WORKFLOW_PERSISTENCE_DURATION_SECONDS: [
        LABEL_MINION_COMPOSITE_KEY,
        LABEL_MINION_WORKFLOW_PERSISTENCE_CHECKPOINT_TYPE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_OPERATION,
        LABEL_MINION_WORKFLOW_PERSISTENCE_POLICY,
        LABEL_STATE_STORE,
    ],
    MINION_WORKFLOW_PERSISTENCE_BLOCKED_GAUGE: [
        LABEL_MINION_COMPOSITE_KEY,
        LABEL_MINION_WORKFLOW_PERSISTENCE_CHECKPOINT_TYPE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_OPERATION,
        LABEL_MINION_WORKFLOW_PERSISTENCE_FAILURE_STAGE,
        LABEL_MINION_WORKFLOW_PERSISTENCE_POLICY,
        LABEL_STATE_STORE,
    ],

    MINION_WORKFLOW_STEP_STARTED_TOTAL: [LABEL_MINION_COMPOSITE_KEY, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_INFLIGHT_GAUGE: [LABEL_MINION_COMPOSITE_KEY, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_ABORTED_TOTAL: [LABEL_MINION_COMPOSITE_KEY, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_FAILED_TOTAL: [LABEL_MINION_COMPOSITE_KEY, LABEL_MINION_WORKFLOW_STEP, LABEL_ERROR_TYPE],
    MINION_WORKFLOW_STEP_SUCCEEDED_TOTAL: [LABEL_MINION_COMPOSITE_KEY, LABEL_MINION_WORKFLOW_STEP],
    MINION_WORKFLOW_STEP_DURATION_SECONDS: [LABEL_MINION_COMPOSITE_KEY, LABEL_MINION_WORKFLOW_STEP, LABEL_STATUS],

    SYSTEM_MEMORY_USED_PERCENT: [],
    SYSTEM_CPU_USED_PERCENT: [],

    PROCESS_MEMORY_USED_PERCENT: [],
    PROCESS_CPU_USED_PERCENT: [],
}
