"""Stamp durable UUID config ids into supported config files."""

from __future__ import annotations

import argparse
import json
import re
import uuid
from pathlib import Path
from typing import Any, cast

from minions._internal._domain.config_identity import CONFIG_ID_KEY, validate_config_id

__all__ = ["main"]

_YAML_SUFFIXES = {".yaml", ".yml"}
_SUPPORTED_SUFFIXES = {".toml", ".json", *_YAML_SUFFIXES}
_GENERATED_COMMENT = "# Generated by `minions stamp config-ids`; do not edit manually."
_TOML_CONFIG_ID_ASSIGNMENT_RE = re.compile(rf"^\s*{re.escape(CONFIG_ID_KEY)}\s*=")
_SKIP_DIRS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "htmlcov",
    "venv",
}


def _stamp_toml(source: str, config_id: str) -> tuple[str, bool]:
    for line in source.splitlines():
        if _TOML_CONFIG_ID_ASSIGNMENT_RE.match(line):
            return source, False
    return f'{_GENERATED_COMMENT}\n{CONFIG_ID_KEY} = "{config_id}"\n{source}', True


def _stamp_yaml(source: str, config_id: str) -> tuple[str, bool]:
    for line in source.splitlines():
        if line.strip().startswith(f"{CONFIG_ID_KEY}:"):
            return source, False
    return f'{_GENERATED_COMMENT}\n{CONFIG_ID_KEY}: "{config_id}"\n{source}', True


def _stamp_json(source: str, config_id: str) -> tuple[str, bool]:
    parsed = json.loads(source)
    if not isinstance(parsed, dict):
        raise ValueError("JSON config must be an object to stamp a config id")
    parsed_dict = cast(dict[Any, Any], parsed)
    if CONFIG_ID_KEY in parsed_dict:
        value = parsed_dict[CONFIG_ID_KEY]
        if not isinstance(value, str):
            raise TypeError(f"{CONFIG_ID_KEY} must be a string")
        validate_config_id(value)
        return source, False
    stamped = {CONFIG_ID_KEY: config_id, **parsed_dict}
    return json.dumps(stamped, indent=2, sort_keys=False) + "\n", True


def stamp_file(path: Path, *, dry_run: bool = False) -> bool:
    config_id = str(uuid.uuid4())
    source = path.read_text()
    suffix = path.suffix.lower()
    if suffix == ".toml":
        updated, changed = _stamp_toml(source, config_id)
    elif suffix in _YAML_SUFFIXES:
        updated, changed = _stamp_yaml(source, config_id)
    elif suffix == ".json":
        updated, changed = _stamp_json(source, config_id)
    else:
        raise ValueError(f"Unsupported config file type for {path}: expected .toml, .yaml, .yml, or .json")
    if changed and not dry_run:
        path.write_text(updated)
    return changed


def _iter_config_files(root: Path) -> list[Path]:
    if root.is_file():
        if root.suffix.lower() not in _SUPPORTED_SUFFIXES:
            raise ValueError(
                f"Unsupported config file type for {root}: expected .toml, .yaml, .yml, or .json"
            )
        return [root]
    if not root.is_dir():
        raise FileNotFoundError(root)

    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in _SUPPORTED_SUFFIXES:
            continue
        if any(part.startswith(".") or part in _SKIP_DIRS for part in path.relative_to(root).parts[:-1]):
            continue
        files.append(path)
    return sorted(files)


def expand_paths(paths: list[Path]) -> list[Path]:
    files: list[Path] = []
    for path in paths:
        files.extend(_iter_config_files(path))
    return files


def build_parser(*, prog: str) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog=prog,
        description="Stamp durable UUID config ids into TOML, YAML, and JSON config files.",
    )
    parser.add_argument("paths", nargs="+", type=Path, help="TOML, YAML, or JSON config files or directories to update.")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be stamped without writing files.")
    return parser


def main(argv: list[str] | None = None, *, prog: str = "python -m minions stamp config-ids") -> int:
    parser = build_parser(prog=prog)
    args = parser.parse_args(argv)
    for path in expand_paths(args.paths):
        changed = stamp_file(path, dry_run=args.dry_run)
        if changed:
            action = "would stamp" if args.dry_run else "stamped"
            print(f"{path}: {action} {CONFIG_ID_KEY}")
        else:
            print(f"{path}: already has {CONFIG_ID_KEY}")
    return 0
